export const projects = [
  {
    number: "01",
    title: "Muse",
    year: "2026",
    archiveYear: 2026,
    category: "Solo · ronglab 001",
    description:
      "A small playlist tool that turns songs around a theme into a story-style visual made to be shared.",
    technologies: ["Next.js"],
    image: null,
    imageAlt: "Muse playlist and story preview",
    mediaType: "website",
    previewUrl: "https://muse-dusky.vercel.app/",
    imagePosition: "center",
    href: "https://muse-dusky.vercel.app/",
    featured: true,
    accent: "sage",
    status: "Personal project",
  },
  {
    number: "02",
    title: "Barrel",
    year: "2025–2026",
    archiveYear: 2026,
    category: "Team · AI · Mobile",
    description:
      "A wine and whisky app that lets users scan a bottle, automatically pull out important product details, and save them to a personal archive. I worked on the scan flow from image capture to result display, including OpenAI-based image understanding, prompt design for product lookup, and product image search.",
    technologies: ["Expo", "React Native", "Django", "AWS", "OpenAI API"],
    image: "https://d3ci2dhksvo0zi.cloudfront.net/images/barrel.png",
    imageAlt: "Barrel app logo",
    mediaType: "logo",
    imagePosition: "center",
    href: "https://apps.apple.com/us/app/barrel-%EB%B0%B0%EB%9F%B4/id6754582603",
    featured: false,
    accent: "blue",
    status: "Released in 2026",
  },
  {
    number: "03",
    title: "Gloda",
    year: "2026",
    archiveYear: 2026,
    category: "Team · Backend · Mobile",
    description:
      "A community app for creating and joining groups and events. I worked mainly on the backend, building the authentication flow across Kakao, Naver, and Apple and supporting user safety and account flows such as blocking and suspension.",
    technologies: ["Expo", "React Native", "TypeScript", "Django"],
    image: "https://d3ci2dhksvo0zi.cloudfront.net/images/gloda.jpg",
    imageAlt: "Gloda app logo",
    mediaType: "logo",
    imagePosition: "center",
    href: "https://apps.apple.com/us/app/gloda/id6757652038",
    featured: false,
    accent: "blush",
    status: "Released in 2026",
  },
];
